#pragma once
enum GameScene {
	SCENE_GAME_TITLE,
	SCENE_GAME_CREDIT,
	SCENE_GAME_STAGE_SELECT,
	SCENE_GAME_MENU,
	SCENE_GAME_PLAY_STAGE1,
	SCENE_GAME_PLAY_STAGE2,
	SCENE_GAME_PLAY_STAGE3,
	SCENE_GAME_CLEAR,
};